#!/usr/bin/env python3
"""Rebuild every material analytical result from raw/golden inputs.

All outputs under reports/results are generated by this script on every pipeline run.
The script intentionally avoids machine-specific paths and makes metric grains explicit.
"""
from __future__ import annotations
from pathlib import Path
import argparse
import hashlib
import json
import math
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd
from data_io import read_csv


OBS_START = "2026-01-01"
OBS_END = "2026-08-12"
COMPLETE_MONTHS = [f"2026-{m:02d}" for m in range(1, 8)]
JULY = "2026-07"
BUDGET = 100_000_000.0



def next_payment_window_flags(rows: pd.DataFrame, payments: pd.DataFrame, date_col: str, window_days: int) -> tuple[pd.Series, pd.Series]:
    """Return payer flag and next-payment amount using per-account binary search."""
    out_flag = pd.Series(False, index=rows.index)
    out_amt = pd.Series(0.0, index=rows.index)
    pay_groups = {k: g.sort_values('event_at') for k, g in payments.groupby('account_id')}
    for acct, grp in rows.groupby('account_id', sort=False):
        pg = pay_groups.get(acct)
        if pg is None or pg.empty:
            continue
        ptime = pg.event_at.to_numpy(dtype='datetime64[ns]')
        pamt = pg.amount.to_numpy(dtype=float)
        for row_idx, date_value in zip(grp.index, grp[date_col]):
            pos = np.searchsorted(ptime, np.datetime64(date_value) + np.timedelta64(1, 'D'), side='left')
            if pos < len(ptime) and ptime[pos] < np.datetime64(date_value) + np.timedelta64(window_days + 1, 'D'):
                out_flag.at[row_idx] = True
                out_amt.at[row_idx] = pamt[pos]
    return out_flag, out_amt


def last_touch_before_payment(payments: pd.DataFrame, interactions: pd.DataFrame) -> pd.DataFrame:
    """Find latest interaction strictly before each payment using per-account binary search."""
    int_groups = {k: g.sort_values('event_at') for k, g in interactions.groupby('account_id')}
    out = payments[['payment_id','account_id','event_at','amount']].copy()
    out['last_touch_event_at'] = pd.NaT
    out['last_touch_channel'] = None
    for acct, grp in out.groupby('account_id', sort=False):
        ig = int_groups.get(acct)
        if ig is None or ig.empty:
            continue
        it = ig.event_at.to_numpy(dtype='datetime64[ns]')
        for row_idx, pay_time in zip(grp.index, grp.event_at):
            pos = np.searchsorted(it, np.datetime64(pay_time), side='left') - 1
            if pos >= 0:
                out.at[row_idx, 'last_touch_event_at'] = ig.iloc[pos].event_at
                out.at[row_idx, 'last_touch_channel'] = ig.iloc[pos].channel
    return out

def load(repo: Path):
    raw = repo / "raw"
    results = repo / "reports" / "results"
    results.mkdir(parents=True, exist_ok=True)

    calls = read_csv(raw, "calls.csv", parse_dates=["event_at"])
    attempts = read_csv(raw, "call_attempts.csv", parse_dates=["event_at"])
    disp = read_csv(raw, "call_dispositions.csv", parse_dates=["event_at"])
    ptp = read_csv(raw, "promises_to_pay.csv", parse_dates=["event_at", "promised_date"])
    sessions = read_csv(raw, "agent_sessions.csv", parse_dates=["login_at", "logout_at"])
    pay = read_csv(repo / "golden_dataset", "golden_payments.csv", parse_dates=["event_at"])
    targets = read_csv(raw, "daily_targeting.csv", parse_dates=["target_date"])
    accounts = read_csv(raw, "accounts.csv", parse_dates=["opened_at"])
    borrowers = read_csv(raw, "borrowers.csv")
    campaigns = read_csv(raw, "campaigns.csv", parse_dates=["start_at", "end_at"])
    whatsapp = read_csv(raw, "whatsapp_events.csv", parse_dates=["event_at"])
    sms = read_csv(raw, "sms_events.csv", parse_dates=["event_at"])
    field = read_csv(raw, "field_visits.csv", parse_dates=["event_at"])
    vendor = read_csv(raw, "vendor_telephony.csv")
    return raw, results, calls, attempts, disp, ptp, sessions, pay, targets, accounts, borrowers, campaigns, whatsapp, sms, field, vendor


def canon_calls_attempts(calls, attempts, disp):
    calls = calls.sort_values(["call_id", "event_at"]).drop_duplicates("call_id", keep="first").copy()
    attempts = attempts.sort_values(["attempt_id", "event_at"]).drop_duplicates("attempt_id", keep="first").copy()
    attempts = attempts.merge(calls[["call_id", "call_status"]], on="call_id", how="left")
    disp = disp.sort_values(["call_id", "event_at"]).drop_duplicates(["call_id", "disposition_code"], keep="first").copy()
    valid_answered = set(calls.loc[calls.call_status.eq("ANSWERED"), "call_id"])
    disp = disp[disp.call_id.isin(valid_answered)].copy()
    calls["month"] = calls.event_at.dt.to_period("M").astype(str)
    attempts["month"] = attempts.event_at.dt.to_period("M").astype(str)
    disp["month"] = disp.event_at.dt.to_period("M").astype(str)
    return calls, attempts, disp


def targeted_keys(targets):
    t = targets.copy()
    t["month"] = t.target_date.dt.to_period("M").astype(str)
    return t


def audited_pay(pay):
    p = pay.copy()
    p["month"] = p.event_at.dt.to_period("M").astype(str)
    return p[(p.audited_recovery == 1) & (p.payment_status == "SUCCESS")].copy()


def build_operational_metrics(results, calls, attempts, disp, ptp, sessions, pay, targets, accounts):
    rpc_codes = {"PTP", "PROMISE_TO_PAY", "PAID", "CALLBACK", "REFUSED", "DISPUTE"}
    ptp_codes = {"PTP", "PROMISE_TO_PAY"}
    attempt_monthly = attempts.groupby("month").agg(
        attempts=("attempt_id", "nunique"),
        answered=("call_status", lambda s: s.eq("ANSWERED").sum()),
    ).reset_index()
    m = attempt_monthly.copy()
    m["contact_rate"] = m.answered / m.attempts.replace(0, np.nan)

    rpc = disp[disp.disposition_code.isin(rpc_codes)].groupby("month").call_id.nunique().rename("rpc_calls")
    ptpc = disp[disp.disposition_code.isin(ptp_codes)].groupby("month").call_id.nunique().rename("ptp_calls")
    m = m.merge(rpc, on="month", how="left").merge(ptpc, on="month", how="left").fillna(0)
    m["rpc_rate"] = m.rpc_calls / m.answered.replace(0, np.nan)
    m["ptp_rate"] = m.ptp_calls / m.rpc_calls.replace(0, np.nan)

    resolved = ptp[ptp.status.isin(["KEPT", "BROKEN"])].copy()
    resolved["month"] = resolved.promised_date.dt.to_period("M").astype(str)
    prs = resolved.groupby("month").agg(
        kept=("status", lambda s: (s == "KEPT").sum()),
        broken=("status", lambda s: (s == "BROKEN").sum()),
    ).reset_index()
    prs["ptp_kept_rate"] = prs.kept / (prs.kept + prs.broken).replace(0, np.nan)
    m = m.merge(prs, on="month", how="left")

    p = audited_pay(pay)
    p_all = p.groupby("month").agg(audited_cash=("amount", "sum"), audited_payers=("account_id", "nunique")).reset_index()
    t = targets.copy(); t["month"] = t.target_date.dt.to_period("M").astype(str)
    tu = t[["month", "account_id"]].drop_duplicates()
    t_base = tu.merge(accounts[["account_id", "principal_amount"]], on="account_id", how="left")
    tm = t_base.groupby("month").agg(targeted_accounts=("account_id", "nunique"), targeted_principal=("principal_amount", "sum")).reset_index()
    p_t = p.merge(tu, on=["month", "account_id"], how="inner")
    tr = p_t.groupby("month").agg(targeted_audited_cash=("amount", "sum"), targeted_audited_payers=("account_id", "nunique")).reset_index()
    m = m.merge(p_all, on="month", how="left").merge(tm, on="month", how="left").merge(tr, on="month", how="left")
    m = m.fillna({"audited_cash": 0, "audited_payers": 0, "targeted_audited_cash": 0, "targeted_audited_payers": 0, "targeted_accounts": 0, "targeted_principal": 0})
    m["recovery_rate"] = m.targeted_audited_cash / m.targeted_principal.replace(0, np.nan)
    m["recovery_per_targeted_account"] = m.targeted_audited_cash / m.targeted_accounts.replace(0, np.nan)

    ss = sessions.copy(); ss["session_hours"] = ((ss.logout_at - ss.login_at).dt.total_seconds() / 3600).clip(lower=0)
    h = ss.groupby(ss.login_at.dt.to_period("M").astype(str)).session_hours.sum().rename_axis("month").reset_index(name="agent_session_hours")
    m = m.merge(h, on="month", how="left")
    m["recovery_per_agent_hour"] = m.audited_cash / m.agent_session_hours.replace(0, np.nan)
    m["cost_per_rupee_recovered"] = np.nan
    m = m[m.month.str[:4].eq("2026")].sort_values("month")
    m.to_csv(results / "operational_metrics_monthly.csv", index=False)
    return m


def build_targeting_prepost(results, pay, targets):
    july = targets[targets.target_date.dt.to_period("M").astype(str).eq(JULY)].copy()
    first = july.groupby("account_id", as_index=False).target_date.min().rename(columns={"target_date": "first_target_date"})
    x = first.merge(pay[["account_id", "event_at", "amount"]], on="account_id", how="left")
    # Source target is date-only. Therefore the safest defensible historical comparison excludes
    # the entire treatment day. Pre = seven full prior calendar days; post = seven full subsequent days.
    pre_start = x.first_target_date - pd.Timedelta(days=7)
    post_end = x.first_target_date + pd.Timedelta(days=8)
    x["pre7"] = x.event_at.ge(pre_start) & x.event_at.lt(x.first_target_date)
    x["post7"] = x.event_at.ge(post_end - pd.Timedelta(days=7)) & x.event_at.lt(post_end)
    pp = x.groupby("account_id").agg(
        pre7_payer=("pre7", "max"), post7_payer=("post7", "max"),
        pre7_cash=("amount", lambda s: s[x.loc[s.index, "pre7"]].sum()),
        post7_cash=("amount", lambda s: s[x.loc[s.index, "post7"]].sum()),
    ).reset_index()
    pp.to_csv(results / "targeting_pre_post_7d_account_level.csv", index=False)
    pre_payer = float(pp.pre7_payer.mean()); post_payer = float(pp.post7_payer.mean())
    pre_cash = float(pp.pre7_cash.mean()); post_cash = float(pp.post7_cash.mean())
    lift_pp = (post_payer - pre_payer) * 100
    # Legacy diagnostic: any July payment on/before the first target date.
    july_pay = pay[pay.event_at.dt.to_period("M").astype(str).eq(JULY)]
    leak = first.merge(july_pay[["account_id", "event_at"]], on="account_id", how="left")
    leak["pre_target_payment"] = leak.event_at.le(leak.first_target_date)
    pre_target_accounts = int(leak.groupby("account_id").pre_target_payment.max().sum())
    association = pd.DataFrame([
        ["july_first_targeted_accounts", len(first), "count"],
        ["pre7_payer_rate", pre_payer, "rate"],
        ["post7_payer_rate", post_payer, "rate"],
        ["timing_aligned_pre_post_lift_pp", lift_pp, "percentage_points"],
        ["pre7_avg_cash_per_targeted_account", pre_cash, "INR"],
        ["post7_avg_cash_per_targeted_account", post_cash, "INR"],
        ["timing_aligned_cash_change_per_account", post_cash - pre_cash, "INR"],
        ["treated_accounts_with_pre_target_july_payment", pre_target_accounts, "count"],
        ["treated_accounts_with_pre_target_july_payment_pct", pre_target_accounts / len(first), "rate"],
        ["target_day_excluded_entirely", 1, "flag"],
    ], columns=["metric", "value", "unit"])
    association.to_csv(results / "targeting_association.csv", index=False)
    return first, pp, lift_pp, pre_cash, post_cash


def build_break_even(results, pay, targets):
    monthly_target_counts = targets[targets.target_date.dt.to_period("M").astype(str).isin(COMPLETE_MONTHS)].groupby(targets.target_date.dt.to_period("M").astype(str)).account_id.nunique()
    annual_ops = float(monthly_target_counts.mean() * 12)
    july_target_ids = targets[targets.target_date.dt.to_period("M").astype(str).eq(JULY)][["account_id"]].drop_duplicates()
    july_targeted_pay = pay[pay.event_at.dt.to_period("M").astype(str).eq(JULY)].merge(july_target_ids, on="account_id", how="inner")
    avg_targeted_payer = float(july_targeted_pay.amount.sum() / july_targeted_pay.account_id.nunique())
    annual_recovery_base = annual_ops * avg_targeted_payer
    break_even_pp = 100 * BUDGET / annual_recovery_base
    p0 = 0.012883868690434168
    za, zb = 1.959964, 0.841621
    rows = []
    for holdout in [0.05, 0.10]:
        ratio = (1 - holdout) / holdout
        mde = break_even_pp / 100
        p1 = p0 + mde
        n_control = ((za + zb) ** 2 * (p0 * (1 - p0) + p1 * (1 - p1) / ratio)) / (mde ** 2)
        n_total = n_control * (1 + ratio)
        rows.append([holdout, math.ceil(n_control), math.ceil(n_total), p0, p1, 0.05, 0.80, mde * 100])
    power = pd.DataFrame(rows, columns=["holdout_fraction", "min_control_n", "min_total_n", "baseline_payer_rate", "target_payer_rate", "alpha", "power", "mde_pp"])
    power.to_csv(results / "experiment_power.csv", index=False)
    scenarios = []
    for label, lift in [("Downside", 0.5), ("Planning case", 1.0), ("Break-even threshold", break_even_pp), ("Upside", 2.5)]:
        inc = annual_recovery_base * lift / 100
        roi = (inc - BUDGET) / BUDGET
        months = BUDGET / inc * 12 if inc > 0 else np.nan
        scenarios.append([label, lift, inc, roi, months])
    pd.DataFrame(scenarios, columns=["scenario", "incremental_payer_lift_pp", "annual_incremental_recovery_inr", "roi", "break_even_months"]).to_csv(results / "investment_scenarios_full.csv", index=False)
    pd.DataFrame([
        ["annualized_target_account_opportunities", annual_ops],
        ["avg_recovery_per_targeted_payer_july", avg_targeted_payer],
        ["break_even_lift_pp", break_even_pp],
        ["budget", BUDGET],
        ["recommendation", "randomized targeting pilot before scale"],
    ], columns=["metric", "value"]).to_csv(results / "investment_scenario.csv", index=False)
    return annual_ops, avg_targeted_payer, break_even_pp, power


def build_selection_balance(results, accounts, borrowers, attempts, pay, targets):
    # Common fixed pre-period for everyone: June 1-30. All July treatment begins in July.
    j = targets[targets.target_date.dt.to_period("M").astype(str).eq(JULY)].groupby("account_id", as_index=False).agg(first_target_date=("target_date", "min"))
    frame = accounts.merge(j, on="account_id", how="left")
    frame["treated"] = frame.first_target_date.notna()
    borrowers_small = borrowers[["borrower_id", "state", "city"]].drop_duplicates("borrower_id")
    frame = frame.merge(borrowers_small, on="borrower_id", how="left")
    june_start = pd.Timestamp("2026-06-01"); july_start = pd.Timestamp("2026-07-01")
    cpre = attempts[(attempts.event_at >= june_start) & (attempts.event_at < july_start)].copy()
    call_stats = cpre.groupby("account_id").agg(
        prior_call_attempts=("attempt_id", "nunique"),
        prior_answered_attempts=("call_status", lambda s: s.eq("ANSWERED").sum()),
    ).reset_index()
    frame = frame.merge(call_stats, on="account_id", how="left").fillna({"prior_call_attempts": 0, "prior_answered_attempts": 0})
    frame["prior_contact_rate"] = frame.prior_answered_attempts / frame.prior_call_attempts.replace(0, np.nan)
    prior_pay = pay[(pay.event_at >= june_start) & (pay.event_at < july_start)].groupby("account_id").agg(
        prior_payer=("account_id", "nunique"), prior_audited_cash=("amount", "sum")
    ).reset_index()
    frame = frame.merge(prior_pay, on="account_id", how="left").fillna({"prior_payer": 0, "prior_audited_cash": 0})
    frame["prior_payer"] = frame.prior_payer.clip(upper=1).astype(float)
    rows = []
    for col in ["dpd", "outstanding_amount", "principal_amount", "prior_call_attempts", "prior_contact_rate", "prior_audited_cash"]:
        x = frame.loc[frame.treated, col].dropna(); y = frame.loc[~frame.treated, col].dropna()
        pooled = math.sqrt((x.var(ddof=1) + y.var(ddof=1)) / 2) if len(x) > 1 and len(y) > 1 else np.nan
        smd = (x.mean() - y.mean()) / pooled if pooled and pooled > 0 else 0.0
        rows.append([col, "numeric", x.mean(), y.mean(), smd, "June 1-30 common pre-period"])
    for col in ["risk_segment", "loan_type", "state", "city"]:
        tab = pd.crosstab(frame[col], frame.treated, normalize="columns").reindex(columns=[True, False], fill_value=0)
        if len(tab):
            dif = (tab[True] - tab[False]).abs(); k = dif.idxmax()
            rows.append([col, "categorical", tab.loc[k, True], tab.loc[k, False], float(dif.max()), f"max category share difference={k}; common June pre-period"])
    x = frame.loc[frame.treated, "prior_payer"]; y = frame.loc[~frame.treated, "prior_payer"]
    rows.append(["prior_payer", "binary", x.mean(), y.mean(), x.mean() - y.mean(), "June 1-30 common pre-period"])
    pd.DataFrame(rows, columns=["feature", "type", "treated_value", "untreated_value", "imbalance", "interpretation"]).to_csv(results / "selection_balance_july.csv", index=False)


def build_driver_outputs(results, accounts, borrowers, campaigns, calls, attempts, disp, pay, targets, vendor, sessions):
    p = pay.copy(); p["month"] = p.event_at.dt.to_period("M").astype(str)
    p = audited_pay(p)
    t = targets.copy(); t["month"] = t.target_date.dt.to_period("M").astype(str)
    tu = t[["month", "account_id"]].drop_duplicates()
    base = tu.merge(accounts[["account_id", "principal_amount", "dpd", "risk_segment", "loan_type", "borrower_id"]], on="account_id", how="left")
    base = base.merge(borrowers[["borrower_id", "state"]].drop_duplicates("borrower_id"), on="borrower_id", how="left")
    paymonth = p.groupby(["month", "account_id"]).amount.sum().rename("cash")
    payers = p.groupby(["month", "account_id"]).size().rename("has_payment")
    base = base.join(paymonth, on=["month", "account_id"]).join(payers, on=["month", "account_id"])
    base["cash"] = base.cash.fillna(0); base["has_payment"] = base.has_payment.fillna(0)

    def group_month(dim, outname, yield_name="yield"):
        g = base.groupby(["month", dim], dropna=False).agg(targeted_accounts=("account_id", "nunique"), paying_accounts=("has_payment", lambda s: int((s > 0).sum())), cash=("cash", "sum"), principal=("principal_amount", "sum")).reset_index()
        g[yield_name] = g.cash / g.principal.replace(0, np.nan)
        g.to_csv(results / outname, index=False)
    group_month("state", "geography_monthly.csv")
    group_month("loan_type", "loan_monthly.csv")
    group_month("risk_segment", "risk_monthly.csv")
    base["dpd_bucket"] = pd.cut(base.dpd, [-np.inf, 29, 59, 89, 179, 364, np.inf], labels=["0-29", "30-59", "60-89", "90-179", "180-364", "365+"])
    group = base.groupby(["month", "dpd_bucket"], observed=True).agg(targeted_accounts=("account_id", "nunique"), paying_accounts=("has_payment", lambda s: int((s > 0).sum())), cash=("cash", "sum"), principal=("principal_amount", "sum")).reset_index()
    group["recovery_yield"] = group.cash / group.principal.replace(0, np.nan)
    group.rename(columns={"month": "m"}, inplace=True); group.to_csv(results / "dpd_monthly.csv", index=False)

    priority = t.copy(); priority["priority_band"] = pd.cut(priority.priority, [-np.inf, 4, 7, np.inf], labels=["1-4", "5-7", "8+"])
    pb = priority.merge(accounts[["account_id", "principal_amount"]], on="account_id", how="left").merge(p.groupby(["month","account_id"]).amount.sum().rename("cash"), on=["month","account_id"], how="left")
    pb["cash"] = pb.cash.fillna(0)
    pb = pb.drop_duplicates(["month","account_id","priority_band"])
    pg = pb.groupby(["month", "priority_band"], observed=True).agg(targeted_accounts=("account_id","nunique"), cash=("cash","sum"), principal=("principal_amount","sum"), paying_accounts=("cash", lambda s: int((s > 0).sum()))).reset_index()
    pg["yield"] = pg.cash / pg.principal.replace(0,np.nan); pg.rename(columns={"month":"m"}, inplace=True); pg.to_csv(results/'priority_monthly.csv',index=False)

    # Campaign association: 30-day payer outcome, computed via one forward as-of match per target.
    ct = targets.merge(campaigns[["campaign_id","campaign_name","channel","strategy_version","target_definition"]], on="campaign_id", how="left").copy()
    tq = ct[["account_id","target_date","campaign_name","channel","strategy_version","target_definition"]].copy()
    payer_flag, _ = next_payment_window_flags(tq, p[["account_id","event_at","amount"]], "target_date", 30)
    tq["payer30"] = payer_flag.values
    cg = tq.groupby(["campaign_name","channel","strategy_version","target_definition"]).agg(targets=("account_id","size"), payers_30d=("payer30","sum"), accounts=("account_id","nunique")).reset_index()
    cg["payer_rate"] = cg.payers_30d / cg.accounts.replace(0,np.nan)
    cg.to_csv(results/'campaign_association.csv', index=False)

    # Calling hour in local timezone; fallback to vendor timezone if call row lacks it.
    def local_hour(row):
        try:
            return pd.Timestamp(row.event_at).tz_localize("UTC").tz_convert(row.timezone).hour
        except Exception:
            return pd.Timestamp(row.event_at).hour
    c2=calls.copy(); c2["local_hour"]=[local_hour(r) for _,r in c2.iterrows()]
    ch=c2.groupby([c2.event_at.dt.to_period('M').astype(str),'local_hour']).agg(calls=('call_id','nunique'), answer_rate=('call_status',lambda s:(s=='ANSWERED').mean())).reset_index().rename(columns={'event_at':'m'})
    ch.rename(columns={'event_at':'m'}, inplace=True); ch.columns=['m','local_hour','calls','answer_rate']; ch.to_csv(results/'calling_hour.csv',index=False)

    # Vendor call metrics.
    vm=calls.groupby('vendor_id').agg(calls=('call_id','nunique'),answer_rate=('call_status',lambda s:(s=='ANSWERED').mean()),avg_duration_sec=('duration_sec','mean')).reset_index(); vm.to_csv(results/'vendor_call_metrics.csv',index=False)
    # Descriptive agent-month metrics; not causal agent productivity.
    dcall=set(disp[disp.disposition_code.isin({'PTP','PROMISE_TO_PAY','PAID','CALLBACK','REFUSED','DISPUTE'})].call_id)
    dptp=set(disp[disp.disposition_code.isin({'PTP','PROMISE_TO_PAY'})].call_id)
    cc=calls.copy(); cc['rpc_call']=cc.call_id.isin(dcall); cc['ptp_call']=cc.call_id.isin(dptp)
    aa=attempts.groupby(['month','agent_id']).agg(attempts=('attempt_id','nunique'),answered=('call_status',lambda s:s.eq('ANSWERED').sum())).reset_index()
    ak=cc.groupby(['month','agent_id']).agg(rpc_calls=('rpc_call','sum'),ptp_calls=('ptp_call','sum'),talk_seconds=('duration_sec','sum')).reset_index()
    am=aa.merge(ak,on=['month','agent_id'],how='left').fillna({'rpc_calls':0,'ptp_calls':0,'talk_seconds':0})
    am['contact_rate']=am.answered/am.attempts.replace(0,np.nan); am['rpc_rate']=am.rpc_calls/am.answered.replace(0,np.nan); am['ptp_rate']=am.ptp_calls/am.rpc_calls.replace(0,np.nan)
    sh=sessions.copy(); sh['session_hours']=((sh.logout_at-sh.login_at).dt.total_seconds()/3600).clip(lower=0)
    ah=sh.groupby([sh.login_at.dt.to_period('M').astype(str),'agent_id']).session_hours.sum().reset_index(name='session_hours').rename(columns={'login_at':'month'})
    am=am.merge(ah,on=['month','agent_id'],how='left'); am['descriptive_only']=1; am.to_csv(results/'agent_monthly.csv',index=False)

    disp_map=disp.groupby(['disposition_version','disposition_code']).agg(rows=('call_id','size'),unique_calls=('call_id','nunique')).reset_index(); disp_map.to_csv(results/'disposition_mapping.csv',index=False)

    vc=calls[['call_id','vendor_id','timezone','event_at']].merge(vendor[['vendor_id','timezone']].rename(columns={'timezone':'vendor_timezone'}),on='vendor_id',how='left'); vc['timezone_conflict']=vc.timezone.ne(vc.vendor_timezone); vc.to_csv(results/'vendor_timezone_conflict.csv',index=False)

    # Attempt frequency, July payer within 7 full days after each account's first July target.
    july_targets=targets[targets.month.eq(JULY)].copy()
    freq=july_targets.groupby('account_id').size().rename('attempt_frequency').reset_index()
    first=july_targets.groupby('account_id').target_date.min().rename('first_target_date').reset_index().merge(freq,on='account_id')
    payer_flag3, _ = next_payment_window_flags(first, p[['account_id','event_at','amount']], 'first_target_date', 7)
    first['payer'] = payer_flag3.values
    first['band']=pd.cut(first.attempt_frequency,[-np.inf,0,2,5,np.inf],labels=['0','1-2','3-5','6+'])
    af=first.groupby('band',observed=True).agg(accounts=('account_id','nunique'),payers=('payer','sum')).reset_index(); af['payer_rate']=af.payers/af.accounts.replace(0,np.nan); af.to_csv(results/'attempt_frequency_july.csv',index=False)

    return base


def build_channel_and_attribution(results, pay, targets, calls, attempts, whatsapp, sms, field):
    p = pay[["payment_id","account_id","event_at","amount"]].copy()
    t = targets.copy(); t["month"] = t.target_date.dt.to_period("M").astype(str)
    # Mutually exclusive first target touch per account-month.
    first_touch = t.sort_values(["account_id","month","target_date","target_id"]).drop_duplicates(["account_id","month"], keep="first").copy()
    tq = first_touch[["account_id","target_id","target_date","recommended_channel"]].copy()
    matched = tq.copy()
    payer_flag, next_amt = next_payment_window_flags(matched, p[["account_id","event_at","amount"]], "target_date", 7)
    matched["converted"] = payer_flag.values
    matched["cash_within_7d"] = next_amt.values
    cg = matched.groupby("recommended_channel").agg(unique_first_touches=("target_id","nunique"), touches_with_7d_audited_payment=("converted","sum"), cash_within_7d=("cash_within_7d","sum")).reset_index().rename(columns={"recommended_channel":"channel"})
    cg["7d_touch_conversion"] = cg.touches_with_7d_audited_payment / cg.unique_first_touches.replace(0,np.nan)
    cg["attribution"] = "mutually exclusive first targeting touch per account-month; target day excluded"
    cg.rename(columns={"unique_first_touches":"unique_touches"}, inplace=True)
    cg.to_csv(results/'channel_7d_conversion.csv', index=False)

    # Overlapping touch-level diagnostic is retained separately; one payment can qualify multiple touches.
    tq2 = t[["account_id","target_id","target_date","recommended_channel"]].copy()
    om = tq2.copy()
    payer_flag2, next_amt2 = next_payment_window_flags(om, p[["account_id","event_at","amount"]], "target_date", 7)
    om["converted"] = payer_flag2.values
    om["cash_within_7d"] = next_amt2.values
    og = om.groupby("recommended_channel").agg(unique_touches=("target_id","nunique"), touches_with_7d_audited_payment=("converted","sum"), cash_within_7d=("cash_within_7d","sum")).reset_index().rename(columns={"recommended_channel":"channel"})
    og["7d_touch_conversion"] = og.touches_with_7d_audited_payment / og.unique_touches.replace(0,np.nan)
    og["attribution"] = "overlapping touch-level diagnostic; one payment may qualify for multiple touches"
    og.to_csv(results/'channel_7d_conversion_touch_overlap.csv', index=False)

    # Last-touch descriptive attribution to any interaction strictly before payment.
    interactions = pd.concat([
        calls[["account_id","event_at","call_id"]].assign(channel='VOICE', interaction_id=lambda d:d.call_id),
        whatsapp[["account_id","event_at","whatsapp_event_id"]].assign(channel='WHATSAPP', interaction_id=lambda d:d.whatsapp_event_id).drop(columns='whatsapp_event_id'),
        sms[["account_id","event_at","sms_event_id"]].assign(channel='SMS', interaction_id=lambda d:d.sms_event_id).drop(columns='sms_event_id'),
        field[["account_id","event_at","visit_id"]].assign(channel='FIELD', interaction_id=lambda d:d.visit_id).drop(columns='visit_id'),
    ], ignore_index=True).dropna(subset=['event_at']).sort_values(['account_id','event_at'])
    pay2=p[["payment_id","account_id","event_at","amount"]].rename(columns={'event_at':'payment_event_at'}).copy()
    last=last_touch_before_payment(pay2.rename(columns={'payment_event_at':'event_at'}), interactions)
    last.rename(columns={'event_at':'payment_event_at'}, inplace=True)
    last['lag_hours']=(last.payment_event_at-last.last_touch_event_at).dt.total_seconds()/3600
    last[['payment_id','account_id','payment_event_at','amount','last_touch_channel','last_touch_event_at']].to_csv(results/'payment_last_touch.csv',index=False)
    attr=last.dropna(subset=['last_touch_event_at']).copy(); attr['within_7d']=attr.lag_hours.le(168)
    sh=attr.groupby('last_touch_channel').amount.sum().sort_values(ascending=False); shares=sh/sh.sum()*100
    pd.DataFrame([{'audited_payments_with_last_touch':len(attr),'within_7d_pct':attr.within_7d.mean()*100,'median_lag_hours':attr.lag_hours.median(),'p90_lag_hours':attr.lag_hours.quantile(.9),'voice_share_pct':shares.get('VOICE',0),'whatsapp_share_pct':shares.get('WHATSAPP',0),'sms_share_pct':shares.get('SMS',0),'field_share_pct':shares.get('FIELD',0),'interpretation':'Last-touch timing is descriptive attribution only; channel causality is not established.'}]).to_csv(results/'attribution_window_summary.csv',index=False)


def build_mix_and_cohorts(results, pay, targets, accounts):
    p=pay.copy(); p['month']=p.event_at.dt.to_period('M').astype(str); p=audited_pay(p)
    t=targets.copy(); t['month']=t.target_date.dt.to_period('M').astype(str); tu=t[['month','account_id']].drop_duplicates()
    b=tu.merge(accounts[['account_id','dpd','principal_amount','opened_at']],on='account_id',how='left').merge(p.groupby(['month','account_id']).amount.sum().rename('cash'),on=['month','account_id'],how='left'); b['cash']=b.cash.fillna(0)
    b['dpd_bucket']=pd.cut(b.dpd,[-np.inf,29,59,89,179,364,np.inf],labels=['0-29','30-59','60-89','90-179','180-364','365+'])
    jan=b[b.month=='2026-01']; jul=b[b.month=='2026-07']
    a=jan.groupby('dpd_bucket',observed=True).agg(accounts=('account_id','nunique'),cash=('cash','sum'),principal=('principal_amount','sum')).reset_index(); a['yield']=a.cash/a.principal.replace(0,np.nan)
    z=jul.groupby('dpd_bucket',observed=True).agg(accounts=('account_id','nunique'),cash=('cash','sum'),principal=('principal_amount','sum')).reset_index(); z['yield']=z.cash/z.principal.replace(0,np.nan)
    common=sorted(set(a.dpd_bucket.dropna().astype(str)) & set(z.dpd_bucket.dropna().astype(str)))
    total_j=jan.cash.sum()/jan.principal_amount.sum(); total_z=jul.cash.sum()/jul.principal_amount.sum()
    # Recompute common-cohort yield on a standardized common-cohort portfolio, weighted by July principal mix.
    if common:
        aj=a[a.dpd_bucket.astype(str).isin(common)].set_index(a[a.dpd_bucket.astype(str).isin(common)].dpd_bucket.astype(str))
        zj=z[z.dpd_bucket.astype(str).isin(common)].set_index(z[z.dpd_bucket.astype(str).isin(common)].dpd_bucket.astype(str))
        weights=(zj.principal/zj.principal.sum())
        std_j=float((aj.loc[common,'yield']*weights.loc[common]).sum()); std_z=float((zj.loc[common,'yield']*weights.loc[common]).sum())
    else: std_j=np.nan; std_z=np.nan
    mix=pd.DataFrame([
        ['jan_observed_yield', total_j], ['jul_observed_yield', total_z], ['observed_change_pp',(total_z-total_j)*100],
        ['jan_common_cohort_standardized_yield', std_j], ['jul_common_cohort_standardized_yield', std_z], ['common_cohort_change_pp',(std_z-std_j)*100 if pd.notna(std_j) else np.nan],
        ['common_cohorts_included', ', '.join(common)]
    ], columns=['metric','value'])
    mix.to_csv(results/'mix_decomposition.csv',index=False)
    cohort=pd.concat([a.assign(month='2026-01',common_cohort_flag=a.dpd_bucket.astype(str).isin(common)),z.assign(month='2026-07',common_cohort_flag=z.dpd_bucket.astype(str).isin(common))],ignore_index=True)
    cohort.to_csv(results/'cohort_effects.csv',index=False)
    cohort[cohort.common_cohort_flag].to_csv(results/'cohort_effects_common.csv',index=False)


def build_vendor(results, calls, disp, vendor):
    vd=disp.merge(calls[['call_id','vendor_id','call_status']],on='call_id',how='left').copy(); vd['month']=vd.event_at.dt.to_period('M').astype(str)
    version_mix=pd.crosstab(vd['month'],vd['disposition_version'],normalize='index').reset_index(); version_mix.to_csv(results/'vendor_disposition_version_mix_monthly.csv',index=False)
    rpc_codes={'PTP','PROMISE_TO_PAY','PAID','CALLBACK','REFUSED','DISPUTE'}
    byver=vd.groupby('disposition_version').agg(rows=('call_id','size'),unique_calls=('call_id','nunique'),rpc_rows=('disposition_code',lambda x:x.isin(rpc_codes).sum())).reset_index(); byver['rpc_code_share']=byver.rpc_rows/byver.rows.replace(0,np.nan); byver.to_csv(results/'vendor_disposition_version_mapping.csv',index=False)
    code_map={'PTP':'PTP','PROMISE_TO_PAY':'PTP','PAID':'RPC_PAID','CALLBACK':'RPC_CALLBACK','REFUSED':'RPC_REFUSED','DISPUTE':'RPC_DISPUTE','NO_CONTACT':'NO_CONTACT','PTP_BROKEN':'PTP_BROKEN','WRONG_NUMBER':'WRONG_NUMBER'}
    vd['normalized_outcome']=vd.disposition_code.map(code_map).fillna('OTHER')
    mapping=vd.groupby(['disposition_version','disposition_code','normalized_outcome']).agg(rows=('call_id','size'),unique_calls=('call_id','nunique')).reset_index(); mapping.to_csv(results/'vendor_disposition_code_mapping.csv',index=False)
    before=vd[vd.event_at<pd.Timestamp('2026-05-01')].groupby('disposition_code').size().rename('before_rows'); after=vd[vd.event_at>=pd.Timestamp('2026-05-01')].groupby('disposition_code').size().rename('after_rows')
    change=mapping.groupby(['disposition_code','normalized_outcome']).rows.sum().reset_index().merge(before,on='disposition_code',how='left').merge(after,on='disposition_code',how='left').fillna(0); change.to_csv(results/'vendor_disposition_before_after.csv',index=False)
    spread=(version_mix.drop(columns=['month']).max(axis=1)-version_mix.drop(columns=['month']).min(axis=1)).max() if len(version_mix) else 0
    finding=pd.DataFrame([{
        'finding':'Disposition-version temporal stability',
        'max_monthly_version_mix_spread_pp':spread*100,
        'rpc_code_share_min_pct':byver.rpc_code_share.min()*100,
        'rpc_code_share_max_pct':byver.rpc_code_share.max()*100,
        'conclusion':'No distributional break is evident after version-normalized grouping; semantic equivalence across versions cannot be conclusively established without an authoritative vendor disposition dictionary.'
    }])
    finding.to_csv(results/'vendor_disposition_finding.csv',index=False)


def build_call_hour(results, calls):
    def local_hour(row):
        try:
            return pd.Timestamp(row.event_at).tz_localize('UTC').tz_convert(row.timezone).hour
        except Exception:
            return pd.Timestamp(row.event_at).hour
    c=calls.copy(); c['local_hour']=[local_hour(r) for _,r in c.iterrows()]
    out=c.groupby([c.event_at.dt.to_period('M').astype(str),'local_hour']).agg(calls=('call_id','nunique'),answer_rate=('call_status',lambda s:(s=='ANSWERED').mean())).reset_index(); out.columns=['m','local_hour','calls','answer_rate']; out.to_csv(results/'calling_hour.csv',index=False)


def build_denominator(results, pay, targets, accounts):
    months=sorted(pay.month.unique()); d=pd.DataFrame({'month':months,'all_accounts_master':len(accounts)})
    d=d.merge(targets.groupby('month').account_id.nunique().rename('targeted_accounts'),on='month',how='left').merge(pay.groupby('month').account_id.nunique().rename('audited_payers'),on='month',how='left').fillna(0)
    d['targeted_share_of_master']=d.targeted_accounts/d.all_accounts_master; d['payer_share_of_master']=d.audited_payers/d.all_accounts_master; d['denominator_definition']='All-account recovery uses audited payments; targeted yield uses targeted principal; no success-only denominator.'
    d.to_csv(results/'denominator_audit.csv',index=False)


def build_legacy_propensity(results, accounts, targets, pay):
    # Transparent quintile proxy based on pre-treatment risk/financial profile; this is retained only as a diagnostic.
    july=targets[targets.month.eq(JULY)][['account_id']].drop_duplicates(); july['treated']=1
    frame=accounts[['account_id','dpd','outstanding_amount','principal_amount','risk_segment','loan_type']].copy().merge(july,on='account_id',how='left').fillna({'treated':0})
    # A simple deterministic score is preferable to an opaque model for a diagnostic file.
    score=(frame.dpd.rank(pct=True)*0.35 + frame.outstanding_amount.rank(pct=True)*0.25 + frame.principal_amount.rank(pct=True)*0.20 + frame.risk_segment.map({'HIGH':1,'MEDIUM':0.5,'LOW':0}).fillna(0.5)*0.20)
    frame['propensity_quintile']=pd.qcut(score,5,labels=[1,2,3,4,5],duplicates='drop')
    payer=pay[pay.month.eq(JULY)].groupby('account_id').size().rename('payer')
    frame=frame.join(payer,on='account_id').fillna({'payer':0}); frame['payer']=(frame.payer>0).astype(int)
    g=frame.groupby('propensity_quintile',observed=True).agg(targeted_n=('treated','sum'),untargeted_n=('treated',lambda s:int((s==0).sum())),targeted_july_payer_rate=('payer',lambda s:float(s[frame.loc[s.index,'treated']==1].mean()) if (frame.loc[s.index,'treated']==1).any() else np.nan),untargeted_july_payer_rate=('payer',lambda s:float(s[frame.loc[s.index,'treated']==0].mean()) if (frame.loc[s.index,'treated']==0).any() else np.nan)).reset_index()
    g['legacy_rate_diff']=g.targeted_july_payer_rate-g.untargeted_july_payer_rate
    g.to_csv(results/'legacy_propensity_sensitivity.csv',index=False)


def build_confidence(results):
    pp=pd.read_csv(results/'targeting_pre_post_7d_account_level.csv')
    diff=pp.post7_payer.astype(int)-pp.pre7_payer.astype(int)
    rng=np.random.default_rng(20260912)
    boots=np.array([rng.choice(diff,size=len(diff),replace=True).mean()*100 for _ in range(5000)])
    lo,hi=np.quantile(boots,[.025,.975])
    pd.DataFrame([{'estimate_pp':diff.mean()*100,'ci_low_pp':lo,'ci_high_pp':hi,'method':'paired bootstrap, 5,000 resamples, target day excluded','causal':False}]).to_csv(results/'targeting_descriptive_confidence.csv',index=False)


def build_summary(results, annual_ops, avg_targeted_payer, break_even_pp, lift_pp):
    summary=json.loads((results/'summary.json').read_text())
    exp=pd.read_csv(results/'experiment_power.csv')
    n10=int(exp.loc[exp.holdout_fraction.eq(0.10),'min_total_n'].iloc[0])
    mde10=float(exp.loc[exp.holdout_fraction.eq(0.10),'mde_pp'].iloc[0])
    summary.update({
        'timing_aligned_pre_post_7d_payer_lift_pp':lift_pp,
        'historical_signal_target_day_excluded':True,
        'annualized_target_account_opportunities':annual_ops,
        'break_even_lift_pp':break_even_pp,
        'avg_recovery_per_targeted_payer_july':avg_targeted_payer,
        'counterfactual_primary_statistical_endpoint':'30-day payer rate',
        'counterfactual_financial_decision_metric':'30-day audited cash per eligible account',
        'selection_balance_window':'June 1-30 fixed common pre-period for both July treated and untreated accounts',
        'channel_conversion_definition':'Mutually exclusive first targeting touch per account-month; next 7 full calendar days; target day excluded',
        'golden_account_month_temporal_caveat':'Account-table attributes are labeled current/extract-level, not historical monthly snapshots.',
        'preferred_holdout_fraction':0.10, 'planning_mde_pp':mde10, 'planning_power':0.80, 'planning_alpha':0.05, 'planning_total_n_10pct_holdout':n10,
        'operational_metric_definitions':'reports/Metric_Dictionary.md', 'statistical_investigation':'reports/Statistical_Investigation.md', 'data_contracts_and_lineage':'reports/Data_Contracts_and_Lineage.md',
        'data_limitations':['client','language','agent_tenure','dedicated_borrower_segment','cost_per_rupee_recovered','historical_dpd_snapshots','target_timestamp']
    })
    (results/'summary.json').write_text(json.dumps(summary,indent=2,ensure_ascii=False),encoding='utf-8')


def write_manifest(results):
    expected=[
        'summary.json','monthly_metrics.csv','operational_metrics_monthly.csv','agent_monthly.csv','cohort_effects.csv','cohort_effects_common.csv',
        'selection_balance_july.csv','denominator_audit.csv','experiment_power.csv','investment_scenarios_full.csv','investment_scenario.csv',
        'vendor_disposition_finding.csv','vendor_disposition_version_mix_monthly.csv','vendor_disposition_version_mapping.csv','vendor_disposition_code_mapping.csv','vendor_disposition_before_after.csv',
        'attribution_window_summary.csv','targeting_descriptive_confidence.csv','targeting_pre_post_7d_account_level.csv','targeting_association.csv',
        'channel_7d_conversion.csv','channel_7d_conversion_touch_overlap.csv','payment_last_touch.csv','calling_hour.csv','priority_monthly.csv','campaign_association.csv',
        'geography_monthly.csv','loan_monthly.csv','risk_monthly.csv','dpd_monthly.csv','attempt_frequency_july.csv','mix_decomposition.csv','legacy_propensity_sensitivity.csv',
        'vendor_call_metrics.csv','disposition_mapping.csv','vendor_timezone_conflict.csv','operational_metrics_sql.csv','denominator_audit_sql.csv','cohort_effects_sql.csv'
    ]
    manifest={'generated_files':{},'expected_count':len(expected)}
    missing=[]
    for name in expected:
        p=results/name
        if not p.exists(): missing.append(name); continue
        h=hashlib.sha256(p.read_bytes()).hexdigest()
        manifest['generated_files'][name]=h
    manifest['missing']=missing
    (results/'rebuild_manifest.json').write_text(json.dumps(manifest,indent=2),encoding='utf-8')
    if missing:
        raise RuntimeError(f'Missing generated result files: {missing}')


def build(repo):
    repo = Path(repo).resolve()
    raw, results, calls, attempts, disp, ptp, sessions, pay, targets, accounts, borrowers, campaigns, whatsapp, sms, field, vendor=load(repo)
    calls, attempts, disp=canon_calls_attempts(calls,attempts,disp)
    targets['month']=targets.target_date.dt.to_period('M').astype(str)
    pay['month']=pay.event_at.dt.to_period('M').astype(str)
    pay=audited_pay(pay)
    build_operational_metrics(results,calls,attempts,disp,ptp,sessions,pay,targets,accounts)
    build_legacy_propensity(results,accounts,targets,pay)
    first,pp,lift,pre_cash,post_cash=build_targeting_prepost(results,pay,targets)
    annual_ops,avg_targeted_payer,break_even_pp,power=build_break_even(results,pay,targets)
    build_selection_balance(results,accounts,borrowers,attempts,pay,targets)
    base=build_driver_outputs(results,accounts,borrowers,campaigns,calls,attempts,disp,pay,targets,vendor,sessions)
    build_channel_and_attribution(results,pay,targets,calls,attempts,whatsapp,sms,field)
    build_mix_and_cohorts(results,pay,targets,accounts)
    build_vendor(results,calls,disp,vendor)
    build_call_hour(results,calls)
    build_denominator(results,pay,targets,accounts)
    build_confidence(results)
    build_summary(results,annual_ops,avg_targeted_payer,break_even_pp,lift)
    write_manifest(results)
    print(f'Supplementary metrics complete: {len(json.loads((results/"rebuild_manifest.json").read_text())["generated_files"])} outputs regenerated.', flush=True)


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',default=Path(__file__).resolve().parents[1]); args=ap.parse_args(); build(Path(args.repo_root).resolve())

if __name__=='__main__':
    main()
